version: 1.1
kind: operation
name: build
params:
  destination:
    value:
      name: polyaxon/polyaxon-quick-start
      connection: docker-connection
runPatch:
  init:
  - dockerfile:
      image: "tensorflow/tensorflow:2.0.1-py3"
      run:
      - 'pip3 install --no-cache-dir -U polyaxon["s3","gcs","azure","polyboard","polytune"]'
      langEnv: 'en_US.UTF-8'
hubRef: kaniko
